import type { LandingContent } from "@/config/content/types";

export const ar: LandingContent = {
  seo: {
    title: "كورسات 3D للطلاب — 3ds Max وV-Ray وCorona",
    description:
      "كورس 3ds Max وV-Ray وCorona مسجّل مسبقاً للطلاب. سجّل بياناتك واحصل على خصم 350 دولار — السعر بعد الخصم 150,000 دينار فقط.",
    ogTitle: "كورس 3D للطلاب — وفّر 350 دولار",
    ogDescription:
      "تعلّم 3ds Max وV-Ray وCorona بسعر طلابي. سجّل مسبقاً واحصل على كوبون الخصم.",
  },
  brand: {
    name: "3D Student Lab",
    shortName: "3D Lab",
  },
  nav: {
    links: [
      { href: "#why-3d", label: "لماذا 3D؟" },
      { href: "#software", label: "البرامج" },
      { href: "#curriculum", label: "تسلسل المواضيع" },
      { href: "#faq", label: "أسئلة" },
    ],
    cta: "احصل على الخصم",
  },
  hero: {
    eyebrow: "كورس مسجّل مسبقاً",
    headline: "طوّر مهاراتك في الـ3D واحصل على",
    headlineAccent: "خصم خاص للطلاب",
    support:
      "الكورس مسجّل مسبقاً: تتعلّم 3ds Max وV-Ray وCorona في الوقت الذي يناسبك. سجّل بياناتك واحصل على كوبون خصم خاص بالطلاب.",
    courseName: "3ds Max + V-Ray + Corona",
    discountLabel: "خصم خاص للمسجلين مسبقاً",
    discountValue: "350$",
    priceLabel: "قيمة الكورس بعد الخصم",
    priceValue: "150,000",
    priceCurrency: "دينار عراقي",
    priceNote: "للطلاب فقط",
    primaryCta: "احصل على كوبون الخصم",
    secondaryCta: "اكتشف تسلسل المواضيع",
    visualCaption: "مشهد معماري — استبدل هذه الصورة برندر حقيقي لاحقاً",
    proof: "تشاهد الدروس في أي وقت · موجّه لطلاب الجامعات",
    formatBadge: "كورس مسجّل مسبقاً",
    formatNote: "هذا العرض للكورس المسجّل مسبقاً، وليس كورساً حضورياً.",
    stats: [
      { value: "350$", label: "خصم خاص للمسجلين مسبقاً" },
      { value: "150 ألف", label: "دينار بعد الخصم" },
      { value: "3", label: "برامج في كورس واحد" },
    ],
  },
  trustBar: {
    label: "البرامج في هذا الكورس",
    items: ["3ds Max", "V-Ray", "Corona Renderer"],
  },
  benefits: {
    eyebrow: "لماذا تتعلّم 3D؟",
    title: "مهارات ترفع مستوى مشاريعك الجامعية",
    intro:
      "البرامج ثلاثية الأبعاد تساعدك على شرح أفكارك بوضوح أكبر، سواء في مشروع التخرج أو في عرض تصميمي.",
    items: [
      {
        id: "projects",
        title: "مشاريع جامعية أوضح",
        description: "حوّل المخططات والأفكار إلى مشاهد يمكن لأساتذتك وزملائك فهمها بسرعة.",
      },
      {
        id: "presentations",
        title: "عروض تقديمية أقوى",
        description: "صورة رندر واحدة غالباً ما توضّح الفكرة أكثر من عدة شرائح نصية.",
      },
      {
        id: "portfolio",
        title: "بورتفوليو مهني",
        description: "ابدأ ببناء أعمال تعرض أسلوبك في التصميم والإظهار المعماري.",
      },
      {
        id: "visualization",
        title: "مهارة الإظهار",
        description: "تعلّم كيف تتحكم بالإضاءة والخامات حتى يبدو المشهد مقنعاً.",
      },
      {
        id: "internships",
        title: "الاستعداد للتدريب",
        description: "كثير من المكاتب تطلب معرفة أساسية ببرامج النمذجة والرندر.",
      },
      {
        id: "freelance",
        title: "أساس للعمل الحر",
        description: "بعد إتقان الأساسيات يمكنك تقديم خدمات إظهار بسيطة بثقة أكبر.",
      },
    ],
  },
  software: {
    eyebrow: "البرامج",
    title: "ثلاثة برامج تكمل بعضها",
    intro: "الكورس المسجّل يركّز على سلسلة عمل واحدة: النمذجة ثم الرندر.",
    cards: [
      {
        id: "max",
        name: "3ds Max",
        tagline: "النمذجة وبناء المشهد",
        points: ["3D Modeling", "Scene Creation", "Architecture Visualization"],
        accent: "gold",
        image: "/images/max-house.jpg",
      },
      {
        id: "vray",
        name: "V-Ray",
        tagline: "رندر احترافي",
        points: ["Professional Rendering", "Lighting", "Materials"],
        accent: "cyan",
        image: "/images/software-vray.jpg",
      },
      {
        id: "corona",
        name: "Corona Renderer",
        tagline: "رندر واقعي للعمارة",
        points: ["Realistic Rendering", "Materials", "Lighting", "Architecture Visualization"],
        accent: "violet",
        image: "/images/software-corona.jpg",
      },
    ],
  },
  curriculum: {
    id: "curriculum",
    eyebrow: "تسلسل المواضيع",
    title: "كيف تُبنى المهارة خطوة بعد خطوة",
    intro:
      "التسلسل منطقي: تتعلّم الأداة أولاً، ثم تبني المشهد، ثم تضيئه، ثم تخرجه. بدون قفزات تربك المبتدئ.",
    steps: [
      {
        id: "interface",
        title: "الواجهة وسير العمل في 3ds Max",
        description: "تتعرّف على الأدوات الأساسية وكيف تتنقل داخل المشهد بدون ضياع.",
      },
      {
        id: "modeling",
        title: "النمذجة المعمارية",
        description: "تبني الكتل والجدران والفتحات والعناصر الأساسية للمشروع.",
      },
      {
        id: "scene",
        title: "تنظيم المشهد والكاميرا",
        description: "ترتّب العناصر وتختار زاوية تُظهر الفكرة بوضوح.",
      },
      {
        id: "materials",
        title: "المواد والخامات",
        description: "تطبّق خامات الجدار، الزجاج، المعدن، والأرضيات بشكل مقروء.",
      },
      {
        id: "lighting",
        title: "الإضاءة",
        description: "تتعلّم إضاءة طبيعية واصطناعية تخدم التصميم ولا تشوّهه.",
      },
      {
        id: "vray",
        title: "الرندر مع V-Ray",
        description: "تُخرج الصورة من نفس المشهد باستخدام V-Ray.",
      },
      {
        id: "corona",
        title: "الرندر مع Corona",
        description: "تعيد إخراج المشهد بـ Corona لفهم الفرق بين المحرّكين.",
      },
      {
        id: "output",
        title: "الإخراج النهائي",
        description: "تحفظ الصورة بجودة مناسبة للعرض الجامعي أو البورتفوليو.",
      },
    ],
    note: "هذا تسلسل تعليمي عام. تفاصيل الدروس تُعرض داخل الكورس نفسه.",
  },
  studentBenefits: {
    eyebrow: "لماذا تبدأ الآن؟",
    title: "الوقت الجامعي هو أفضل وقت للتجربة",
    items: [
      {
        id: "uni",
        title: "مشاريع الجامعة",
        description: "استخدم المهارة على مشروعك الحالي بدل الانتظار حتى التخرج.",
      },
      {
        id: "portfolio",
        title: "البورتفوليو",
        description: "كل رندر تنجزه يصبح جزءاً من ملفك الشخصي.",
      },
      {
        id: "freelance",
        title: "العمل الحر",
        description: "حتى المشاريع الصغيرة تبني خبرة وأسلوباً.",
      },
      {
        id: "career",
        title: "مهارات مهنية",
        description: "الإظهار مهارة مطلوبة في مكاتب العمارة والتصميم.",
      },
      {
        id: "intern",
        title: "التدريب الصيفي",
        description: "معرفة 3ds Max والرندر تسهّل اندماجك في فريق العمل.",
      },
      {
        id: "viz",
        title: "إظهار احترافي",
        description: "تبدأ من مشاهد بسيطة وتتقدم نحو نتائج أقرب للواقع.",
      },
    ],
  },
  discountCta: {
    title: "الطلاب يحصلون على سعر خاص",
    text: "أخبرنا ماذا تدرس وماذا تريد أن تتعلّم، وسنمنحك كوبون خصم طلابي. وفّر 350 دولار عند التسجيل المسبق.",
    cta: "احصل على كوبوني الطلابي",
  },
  futureCourses: {
    eyebrow: "كورسات قادمة",
    title: "أي الكورسات تريد تعلّمها مستقبلاً؟",
    intro: "يمكنك اختيار أكثر من كورس. اختيارك يساعدنا نقرر ما نقدّمه بعد ذلك.",
    cta: "أخبرنا ماذا تريد أن تتعلّم",
    courses: [
      { id: "advanced-corona-vray", name: "رندر متقدم Corona و V-Ray" },
      { id: "intermediate-max-corona-vray", name: "المستوى المتوسط: 3ds Max + Corona + V-Ray" },
      { id: "advanced-max-corona-vray", name: "المستوى المتقدم: 3ds Max + Corona + V-Ray" },
      { id: "autocad", name: "كورس AutoCAD" },
      { id: "photoshop", name: "Photoshop" },
      { id: "media-buying", name: "Media Buying" },
      { id: "motion-design", name: "Motion Design" },
      { id: "office", name: "حزمة الأوفيس" },
      { id: "graduation-research", name: "كتابة بحث التخرج" },
    ],
  },
  form: {
    eyebrow: "التسجيل المسبق",
    title: "احصل على كوبون الخصم الطلابي",
    intro: "النموذج قصير. نحتاجه لنعرف جامعتك واهتمامك ونرسل لك الخصم.",
    groups: {
      personal: "بياناتك",
      university: "دراستك",
      interest: "أي الكورسات تريد تعلّمها مستقبلاً؟",
      location: "استفتاء الحضور",
    },
    fields: {
      fullName: "الاسم الكامل",
      phone: "رقم التواصل الأول",
      phoneSecondary: "رقم التواصل الثاني",
      email: "البريد الإلكتروني",
      emailHint: "اختياري",
      instagram: "حساب إنستغرام",
      governorate: "المحافظة",
      address: "عنوان السكن",
      university: "الجامعة",
      major: "التخصص / القسم",
      academicYear: "المرحلة الدراسية",
      courseInterest: "أي الكورسات تريد تعلّمها مستقبلاً؟",
      attendancePreference: "هل ترغب بأخذ الكورس حضورياً مقابل تكلفة إضافية؟",
      attendanceNote:
        "الكورس الحالي مسجّل مسبقاً. هذا استفتاء فقط لمعرفة إن كنت تريد نسخة حضورية لاحقاً مقابل مبلغ إضافي.",
      baghdadSide: "إذا كان حضورياً، أي جانب يناسبك؟",
      futureCourses: "ما الكورسات الأخرى التي تود تعلّمها؟",
      otherCourse: "اذكر الكورس الآخر",
      marketingConsent:
        "أرغب في استلام معلومات عن الكورسات الجديدة وخصومات الطلاب والعروض القادمة.",
    },
    governorateOptions: [
      { value: "baghdad", label: "بغداد" },
      { value: "basra", label: "البصرة" },
      { value: "nineveh", label: "نينوى" },
      { value: "erbil", label: "أربيل" },
      { value: "sulaymaniyah", label: "السليمانية" },
      { value: "duhok", label: "دهوك" },
      { value: "kirkuk", label: "كركوك" },
      { value: "anbar", label: "الأنبار" },
      { value: "saladin", label: "صلاح الدين" },
      { value: "diyala", label: "ديالى" },
      { value: "wasit", label: "واسط" },
      { value: "babil", label: "بابل" },
      { value: "karbala", label: "كربلاء" },
      { value: "najaf", label: "النجف" },
      { value: "qadisiyyah", label: "القادسية" },
      { value: "muthanna", label: "المثنى" },
      { value: "dhi-qar", label: "ذي قار" },
      { value: "maysan", label: "ميسان" },
    ],
    academicYearOptions: [
      { value: "year-1", label: "السنة الأولى" },
      { value: "year-2", label: "السنة الثانية" },
      { value: "year-3", label: "السنة الثالثة" },
      { value: "year-4", label: "السنة الرابعة" },
      { value: "year-5", label: "السنة الخامسة" },
      { value: "graduate", label: "خريج" },
      { value: "other", label: "أخرى" },
    ],
    courseInterestOptions: [
      { value: "advanced-corona-vray", label: "رندر متقدم Corona و V-Ray" },
      { value: "intermediate-max-corona-vray", label: "المستوى المتوسط: 3ds Max + Corona + V-Ray" },
      { value: "advanced-max-corona-vray", label: "المستوى المتقدم: 3ds Max + Corona + V-Ray" },
      { value: "autocad", label: "كورس AutoCAD" },
      { value: "photoshop", label: "Photoshop" },
      { value: "media-buying", label: "Media Buying" },
      { value: "motion-design", label: "Motion Design" },
      { value: "office", label: "حزمة الأوفيس" },
      { value: "graduation-research", label: "كورس كتابة بحث التخرج" },
      { value: "other", label: "أخرى" },
    ],
    attendanceOptions: [
      { value: "yes-extra", label: "نعم، أريد حضورياً مقابل تكلفة إضافية" },
      { value: "no-recorded", label: "لا، أكتفي بالمسجّل مسبقاً" },
      { value: "maybe", label: "ربما، حسب التكلفة والمكان" },
    ],
    baghdadSideOptions: [
      { value: "rasafa", label: "الرصافة" },
      { value: "karkh", label: "الكرخ" },
      { value: "undecided", label: "لم أحدد بعد" },
    ],
    futureCourseOptions: [
      { value: "advanced-corona-vray", label: "رندر متقدم Corona و V-Ray" },
      { value: "intermediate-max-corona-vray", label: "المستوى المتوسط: 3ds Max + Corona + V-Ray" },
      { value: "advanced-max-corona-vray", label: "المستوى المتقدم: 3ds Max + Corona + V-Ray" },
      { value: "autocad", label: "كورس AutoCAD" },
      { value: "photoshop", label: "Photoshop" },
      { value: "media-buying", label: "Media Buying" },
      { value: "motion-design", label: "Motion Design" },
      { value: "office", label: "حزمة الأوفيس" },
      { value: "graduation-research", label: "كورس كتابة بحث التخرج" },
      { value: "other", label: "أخرى" },
    ],
    submit: "احصل على كوبون الخصم",
    submitting: "جارٍ التجهيز...",
    submitError: "حدث خطأ أثناء الإرسال. حاول مرة أخرى.",
    errors: {
      fullName: "يرجى إدخال الاسم",
      phone: "يرجى إدخال رقم التواصل الأول",
      phoneSecondary: "يرجى إدخال رقم التواصل الثاني",
      email: "صيغة البريد غير صحيحة",
      instagram: "يرجى إدخال حساب إنستغرام",
      governorate: "يرجى اختيار المحافظة",
      address: "يرجى إدخال عنوان السكن",
      university: "يرجى اختيار الجامعة",
      major: "يرجى اختيار التخصص",
      academicYear: "يرجى اختيار المرحلة الدراسية",
      courseInterest: "يرجى اختيار كورس واحد على الأقل",
      attendancePreference: "يرجى الإجابة على استفتاء الحضور",
      baghdadSide: "يرجى اختيار الجانب المناسب",
      otherCourseInterest: "يرجى كتابة اسم الكورس الآخر",
    },
    emailInvalid: "صيغة البريد غير صحيحة",
  },
  success: {
    title: "شكراً لتسجيلك",
    duplicateTitle: "بياناتك مسجّلة مسبقاً",
    subtitle: "سيتم إرسال كوبون الخصم إلى واتساب في أقرب وقت ممكن.",
    duplicateSubtitle: "بياناتك موجودة. سيتم التواصل معك على واتساب لإرسال الكوبون.",
    exploreCta: "استكشف تسلسل المواضيع",
  },
  faq: {
    eyebrow: "أسئلة شائعة",
    title: "قبل ما تسجّل",
    items: [
      {
        id: "who",
        question: "من يمكنه الحصول على خصم الطلاب؟",
        answer:
          "الخصم موجّه لطلاب الجامعات ومن في مرحلة الدراسة أو التخرج ممن يملؤون نموذج التسجيل.",
      },
      {
        id: "experience",
        question: "هل أحتاج خبرة سابقة في الـ3D؟",
        answer: "لا تحتاج خبرة سابقة. التسلسل يبدأ من الأساسيات ثم ينتقل إلى الرندر.",
      },
      {
        id: "format",
        question: "هل الكورس حضوري أم مسجّل مسبقاً؟",
        answer:
          "الكورس الحالي مسجّل مسبقاً. يمكنك مشاهدته في الوقت الذي يناسبك. داخل النموذج يوجد استفتاء إن كنت ترغب بنسخة حضورية مقابل تكلفة إضافية.",
      },
      {
        id: "beginner",
        question: "هل الكورس مناسب للمبتدئين؟",
        answer: "نعم، المسار مرتّب ليبدأ الطالب من الواجهة ثم النمذجة ثم الإضاءة والرندر.",
      },
      {
        id: "software",
        question: "ما البرامج التي سأتعلّمها؟",
        answer: "الكورس المسجّل يغطّي 3ds Max وV-Ray وCorona Renderer.",
      },
      {
        id: "both-renderers",
        question: "هل يمكنني تعلّم V-Ray وCorona معاً؟",
        answer: "نعم. نفس المشهد يُخرج بالمحرّكين حتى تفهم الفرق بينهما.",
      },
      {
        id: "other-courses",
        question: "ما الكورسات الأخرى المتوفرة؟",
        answer:
          "العرض الأساسي حالياً هو كورس 3ds Max وV-Ray وCorona. من النموذج يمكنك اختيار كورسات تريد تعلّمها مستقبلاً مثل المستوى المتوسط والمتقدم، AutoCAD، Photoshop، Media Buying، Motion Design، الأوفيس، وكتابة بحث التخرج.",
      },
      {
        id: "coupon-how",
        question: "كيف أحصل على كوبون الخصم؟",
        answer: "بعد إرسال النموذج، يُولَّد الكوبون تلقائياً ويُرسل إليك على واتساب في أقرب وقت. لا يظهر الكود في الصفحة.",
      },
      {
        id: "coupon-later",
        question: "هل يمكنني استخدام الكوبون لاحقاً؟",
        answer: "بعد استلام الكوبون على واتساب يمكنك استخدامه حسب التعليمات المرفقة معه.",
      },
    ],
  },
  finalCta: {
    title: "مهارتك القادمة يمكن أن تغيّر مشاريعك الجامعية",
    text: "سجّل الآن واحصل على خصم 350 دولار. السعر بعد الخصم 150,000 دينار للطلاب.",
    cta: "احصل على خصمي الطلابي",
  },
  help: {
    title: "واجهتك أي مشكلة؟",
    intro: "تواصل معنا وسنساعدك.",
    instagramLabel: "إنستغرام",
    whatsappLabel: "واتساب",
  },
  footer: {
    note: "",
    rights: "جميع الحقوق محفوظة",
  },
  stickyCta: {
    label: "احصل على الكوبون",
    price: "150,000 د.ع",
  },
};
